### ISSUE TITLE
VUEX

### ISSUE THREAD

**Issue by ruzzland** [SRG-community/SRG#1]
Introduce vuex state manager.

**Comment by SanSan-** [comment]
- при логине автоматом пусть переходит во вью MyGames
- при логауте соответственно наоборот....
-  баланс и имя пользователя вынести нарн в шапку
- на странице MyGames сделать фиктивный список подключенных игр
-- с картинками и балансом в каждой игре
-- кнопками "поделиться ссылкой"

**Comment by ruzzland** [comment]
Done
