### ISSUE TITLE
Spring routing: This application has no explicit mapping for /error

### ISSUE THREAD

**Issue by SanSan-** [SRG-community/SRG#3]
> This application has no explicit mapping for /error, so you are seeing this as a fallback
![srg 2017-10-03 23-47-25](https://user-images.githubusercontent.com/9320026/31148455-6faeb406-a895-11e7-870c-8d06694604fa.png)

If you try to load page '/login' directly, you got this error. As one of way to resolve this problem, u may read this [so-ticket](https://stackoverflow.com/questions/31134333/this-application-has-no-explicit-mapping-for-error)

**Comment by ruzzland** [comment]
Fixed
